#:schema node_modules/wrangler/config-schema.json
name = "sublink-workera"
main = "src/worker.jsx"
compatibility_date = "2024-07-24"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "SUBLINK_KV", id = "aa8727a0d5a145498e26f3a51de2deaa" }
]

[assets]
directory = "./public"
